// <auto-generated />
using System;
using Cine.Nucleo.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cine.Nucleo.Datos.Migraciones
{
    [DbContext(typeof(CineDbContext))]
    [Migration("20260819002628_InicialCatalogoYCartelera")]
    partial class InicialCatalogoYCartelera
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cine.Nucleo.Dominio.ButacaNoVendibleFuncion", b =>
                {
                    b.Property<int>("FuncionId")
                        .HasColumnType("int");

                    b.Property<string>("Fila")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("FuncionId", "Fila", "Numero");

                    b.ToTable("ButacaNoVendibleFuncion", (string)null);
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.ButacaSala", b =>
                {
                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<string>("Fila")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<bool>("EsVendible")
                        .HasColumnType("bit");

                    b.HasKey("SalaId", "Fila", "Numero");

                    b.ToTable("ButacaSala", (string)null);

                    b.HasData(
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 1,
                            EsVendible = false
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "A",
                            Numero = 12,
                            EsVendible = false
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "B",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "C",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "D",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "E",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "F",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "G",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "H",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "I",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 6,
                            EsVendible = false
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 1,
                            Fila = "J",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "A",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "B",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "C",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "D",
                            Numero = 12,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 1,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 2,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 3,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 4,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 5,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 6,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 7,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 8,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 9,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 10,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 11,
                            EsVendible = true
                        },
                        new
                        {
                            SalaId = 2,
                            Fila = "E",
                            Numero = 12,
                            EsVendible = true
                        });
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.Funcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AforoVendible")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("InicioLocal")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaId", "InicioLocal");

                    b.ToTable("Funcion", (string)null);
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.OcupacionButaca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartadoId")
                        .HasColumnType("int");

                    b.Property<int?>("BoletoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("FuncionId")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncionId", "Fila", "Numero")
                        .IsUnique();

                    b.ToTable("OcupacionButaca", (string)null);
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClasificacionEdad")
                        .HasColumnType("int");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Pelicula", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClasificacionEdad = 0,
                            DuracionMinutos = 100,
                            Titulo = "El Último Autobús"
                        },
                        new
                        {
                            Id = 2,
                            ClasificacionEdad = 12,
                            DuracionMinutos = 120,
                            Titulo = "Noche de Tormenta"
                        },
                        new
                        {
                            Id = 3,
                            ClasificacionEdad = 16,
                            DuracionMinutos = 95,
                            Titulo = "Camino al Volcán"
                        });
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TotalButacas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sala", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sala 1",
                            TotalButacas = 120
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Sala 2",
                            TotalButacas = 60
                        });
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.ButacaNoVendibleFuncion", b =>
                {
                    b.HasOne("Cine.Nucleo.Dominio.Funcion", "Funcion")
                        .WithMany("ButacasNoVendibles")
                        .HasForeignKey("FuncionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcion");
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.ButacaSala", b =>
                {
                    b.HasOne("Cine.Nucleo.Dominio.Sala", "Sala")
                        .WithMany("Butacas")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.Funcion", b =>
                {
                    b.HasOne("Cine.Nucleo.Dominio.Pelicula", "Pelicula")
                        .WithMany()
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine.Nucleo.Dominio.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.OcupacionButaca", b =>
                {
                    b.HasOne("Cine.Nucleo.Dominio.Funcion", "Funcion")
                        .WithMany()
                        .HasForeignKey("FuncionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcion");
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.Funcion", b =>
                {
                    b.Navigation("ButacasNoVendibles");
                });

            modelBuilder.Entity("Cine.Nucleo.Dominio.Sala", b =>
                {
                    b.Navigation("Butacas");
                });
#pragma warning restore 612, 618
        }
    }
}
